version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: admission-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: admissiondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  admission-api:
    build: .
    container_name: admission-api
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://admin:admin123@postgres:5432/admissiondb?sslmode=disable
      - JWT_SECRET=S1@Anupam
    ports:
      - "8080:8080"

volumes:
  pgdata: